### PR TITLE
Fix for issue #440

### PR DESCRIPTION
**Pull request by cappetta**
Potential fix for https://github.com/dtag-dev-sec/tpotce/issues/440

### CODE REVIEW

**Comment by t3chn0m4g3** [comment]
Thanks for the PR, however it is intended to only support SID.

**Comment by Oogy** [comment]
> Thanks for the PR, however it is intended to only support SID.

Perhaps support for Stable versions should be considered? A single broken package(fuse) has rendered T-Pot uninstallable.

**Comment by t3chn0m4g3** [comment]
@Oogy We had similar problems with stable branches in Ubuntu as well. Mistakes happen and are usually fixed very fast. Turns out Debian `SID` prooved to be even more stable than Ubuntu LTS editions.

**Comment by Oogy** [comment]
@t3chn0m4g3 Fair enough. Thank you for the reply.

**Comment by t3chn0m4g3** [comment]
@Oogy Thanks for understanding.

**Pull request closed without merging**
