### PR TITLE
17.10 Fork - 4 x Unique Conpot Containers in Parallel

### PR DESCRIPTION
**Pull request by UncleRaymondo**
Hi Team,

I've managed to fork off 17.10 and re-configure the platform to run 4 x Conpot Containers in Parallel using 4 different templates, with overlapping ports removed. Each of these containers are also operating with their own users, own groups, own log files, i.e. completely isolated. The only common denominator between each of these containers is the usage of the conpot:1710 image.

All required files as far as I can determine have been updated accordingly; DPS is reporting all healthy. 

Appreciate your review below and if it meet your requirements, merge into 17.10a or 18.04 as required.

Hope this is of help to you.

Cheers,
Ray

### CODE REVIEW

**Comment by t3chn0m4g3** [comment]
Thank you. I hope you do not mind if I will be cherry picking though, since I am following a different angle already (porting back from a different project I am working on [currently](https://github.com/t3chn0m4g3/hp/tree/master/conpot)).

**Comment by t3chn0m4g3** [comment]
Just noticed. You introduced different log paths which will not be available within logstash, hence no visualization in ELK.

**Comment by UncleRaymondo** [comment]
By all means, go for it :) - You know the platform better than I do ;)

I've merged these changes to my live honeypot, still testing - the original conpot, which is now renamed conpot_kamstrup seems to be working fine with nmap returning those ports as open, however the other 3 (conpot_default, conpot_guardianast, conpot_IEC104) are having all their ports returning as closed which means they're being rejected at the docker layer (it would appear as filtered if it was at the firewall)

The IPTables rules are all in, the ports are listening, netstat -luntp shows them as active via the docker-proxy, each of their docker-compose and related files have the new port definitions... interesting to see why its reporting closed...

**Comment by UncleRaymondo** [comment]
Oh... I wonder if I should then keep them all the same log path as the original... thoughts?

**Comment by t3chn0m4g3** [comment]
I was thinking letting [logstash.conf](https://github.com/dtag-dev-sec/tpotce/blob/master/docker/elk/logstash/dist/logstash.conf) point to `conpot.*` or `*.json`. You could use a volume and map it into the logstash container then.

**Comment by UncleRaymondo** [comment]
Hmm... I named them as different paths given that we don't want the conpot.log or conpot.json file to be overwritten or cause a file access error when accessed by multiple containers (not sure if that would actually happen, just thinking out loud)

If logstash can use a `conpot*.* ` and it would read the files for visualisation, I have no issue with that. Although it would be ideal if in the Honeypot Events visualisation there was segmentation between conpot_default or conpot_kamstrup, etc., for the first attempt I have no issues if they all appeared as from the "conpot" honeypot

**Comment by t3chn0m4g3** [comment]
Ahh yes, for your image / container that is correct... My plans involve different logfiles:
```
CMD /usr/bin/conpot --template $CONPOT_TEMPLATE --logfile $CONPOT_LOG --config $CONPOT_CONFIG
```

**Comment by t3chn0m4g3** [comment]
You could do that for your setup as well. Just set ENVs in the `docker-compose.yml`

**Comment by UncleRaymondo** [comment]
Well now this is interesting...

image

The rules are there...

image

It's as if the last two IPTables rules are ignored? Weird?

**Comment by t3chn0m4g3** [comment]
Nope, that is iptables. You need to unload the rules in the oppsoite order.

**Comment by UncleRaymondo** [comment]
Ah crap, look at the error... in the Remove section I have ExecStartPre not ExecStopPost... 

Bloody copy/paste...

**Comment by t3chn0m4g3** [comment]
Ahh yes 😄 I also experienced removing rules in reverse order solved some issues for me with regard to NFQ.

**Comment by UncleRaymondo** [comment]
Hmmm.. no go...

Tried the rules in reverse order for the Remove section, did not help. Have now merged all the ports into a single TCP rule, still no go. It's specific to the ports of those new containers. Those ports are `102, 502, 47808, 161/udp, 10001, 2404`... Every other port loads fine and I can see them as open from another box using nmap...

image

The `DOCKER` chain within IPTables shows the ports are there:

image

`tpot.service` is fine

image

This is the `docker-compose.yml` for the `conpot_IEC404` - does anything look out of order to you?

image

This one is the original `conpot` now renamed `conpot_kamstrup` - This one works fine...

image


Appreciate your thoughts as I'm running out of hair to pull :(

**Comment by t3chn0m4g3** [comment]
1. mulitport only allows for the use of 15 ports at the same time (https://linux.die.net/man/8/iptables)
2. you have to completely flush iptables rules before re-applying (`iptables -F, iptables -X`)
3. NFQ rule always has to be the last rule when appending or all traffic will be redirected to honeytrap

**Comment by UncleRaymondo** [comment]
15 ports only? Sounds backwards lol... Let me try the above and see how it goes :)

**Comment by UncleRaymondo** [comment]
Nope - still nothing... it's as if it's not reading the tpot.service file correctly...

'tpot.service status`

image

`tpot.service config`

image

However, I think I have found the problem! Although, this may be a "by design" issue...

image

That's me accessing the conpot_IEC104 container which shows that it's listening on TCP/2404 which is the correct port... although... it's not listening on TCP/2404. Loading a bash shell inside the container and checking netstat shows that it's running the default conpot ports per the original 17.10 build - I'm guessing this is as built and we're using the conpot:1710 image?

Does this now mean we need to build new images for each of the conpot containers with their respective ports for the respective template?

I'm off to bed now so we'll discuss soon. Have a great day/night!

**Comment by UncleRaymondo** [comment]
OK - did some further investigations... it definitely seems that the conpot DockerFile and/or docker-compose.yml are being ignored durng a build, given that syslog is showing that it's loading the kamstrup_382 template even when the default or guardian_ast templates are configured for usage in the DockerFile and docker-compose.yml files

tpotsyslogconpot

Also looking at the image definition, I find: https://microbadger.com/images/dtagdevsec/conpot:1710 - there is a CMD within that image for the kamstrup_382 template. I can't say for sure as I'm not familiar with this deployment method, but could this CMD be overwriting the pre-defined commands?

Still scratching my head, but still looking for answers... :)

**Comment by UncleRaymondo** [comment]
Verification of open ports to 3 x Conpot Honeypots + other missing ports from original configuration

3_conpot_operational_ports_open

**Comment by UncleRaymondo** [comment]
Verification of 3 x Conpot Honeypots in Parallel, all required ports open

3_conpot_operational_ports_open

image

image

image

**Comment by cheo2322** [comment]
Hi Sir, can you share the .iso including the multiple-conpot? (I suppose that just changing the files on the installed T-Pot 17.10 is not enough to get the multiple-conpot) Because I cannot get the tpot.iso using ./makeiso.sh, I just get mini.iso even when I use the T-Pot 17.10 without the multiple-Conpot. I will be very grateful.

**Comment by cheo2322** [comment]
Hi Sir, it is a very helpful job!

Is already available this multi-conpot? I have created a .iso downloading it but also I get the single conpot. How can I get this multi-conpot?

**Comment by cheo2322** [comment]
Hi Sir, nice contribution! I have a question: Is it visualized the traffic in the same dashboard (ConPot) using Kibana? In this case, Will it be better giving one single dashboard for each conpot PLC, will not?

**Comment by t3chn0m4g3** [comment]
@UncleRaymondo Thanks for submitting. We were working on it in parallel though, so I just did dome cherry picking :bowtie: You can test drive the 18.04 branch and have a look.

@cheo2322 This will be available in the T-Pot 18.10 release which will be available in Q4 this year. You can adjust the dashboards to your liking.

**Pull request closed without merging**
