### PR TITLE
Added Ansible T-Pot Deployment on Open Telekom Cloud

### PR DESCRIPTION
**Pull request by TheHADILP**
- All files under `cloud/open-telekom-cloud` folder
- Reusable Ansible Playbooks for all cloud providers (under `cloud/open-telekom-cloud/ansible`)
- Example Showcase with our Open Telekom Cloud (`deploy_ansible_otc_t-pot.sh`)

### CODE REVIEW

**Comment by t3chn0m4g3** [comment]
@TheHADILP This is awesome! Thank you.

**Comment by t3chn0m4g3** [comment]
@vorband Looks good to me, can you have a look as well?

**Comment by TheHADILP** [comment]
I just want to check in on the hostname issue that we discussed on thursday.
The hostname (e.g. tpot-otc-xyzxyz) is indeed visible on the management interface.
I am currently figuring out, why the hostname from the install script is not respected.

**Comment by t3chn0m4g3** [comment]
In case it will stick with it I would recommend a random name without T-Pot in it.

**Comment by TheHADILP** [comment]
Fixed in https://github.com/dtag-dev-sec/tpotce/pull/356/commits/17073c3a159006c81f9b534d27ec974efe27bb4a.
We now check if cloud-init is used and set an option to preserve the hostname on reboot.
Cloud-init is used in cloud server deployment (found in Azure, AWS, Open Telekom Cloud).

**Comment by t3chn0m4g3** [comment]
After reviewing the changes I vaguely remember that with Ubuntu 18.04 I had the same issues and the solution was the same ;-)

**Pull request merged**
